name: Test Hugo Cleanup

on:
  workflow_run:
    workflows: ['Cleanup Hugo site staging']
    types: [completed]

jobs:
  no-op:
    runs-on: ubuntu-latest
    if: ${{ github.repository != vars.MAIN_REPO }}
    steps:
      - name: Skip on forks
        run: echo "Skipping test on fork repository"

  check_pr1_deployment_count:
    runs-on: ubuntu-latest
    if: ${{ github.repository == vars.MAIN_REPO }}
    steps:
      # TODO: maybe make extract the right PR and check against any PR?
      # Always checking against pr-1 should also be true, since it is
      # idempotent, but would be nice to have more thorough testing
      - name: Test pr-1 branch cleanup
        uses: omsf/static-site-tools/test-deployment-count@main
        with:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          branch_name: pr-1
          n_deployments: 1
